### ISSUE TITLE
3He polarization in dependence of wavelength?

### ISSUE THREAD

**Issue by astellhorn** [scipp/esspolarization#17]
- Would it be better to (i) take a mean popt for all wavelength, or (ii) compute it just for one wavelength, or (iii) have single parameters for all wavelength?
- Maybe can use reduce_dims=['wavelength'] of the scipp.curve_fit (see example)
- related to branch 'calculation-he3-polarization'

**Comment by SimonHeybrock** [comment]
Conclusion:
- Yes, we want wavelength-independent params.
- Just do a 2-D fit.
