### ISSUE TITLE
Functional vs. time-discretized polarization correction

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/esspolarization#24]
Collecting some thoughts after the discussion last week about whether the transmission correction should be represented as a function (that can be evaluated at any precise time) vs. a discretized version (a `scipp.DataArray`).

- There may be performance implications, but it is not a priori clear that one of them is better or excluded. We need to look into the full equations to make a judgement (requires #16).
- The data reduction workflow must perform normalization, e.g., to monitors. Therefore, monitor data must be averaged over a certain time interval. Events can keep higher time resolution, but given that the monitors cannot, does it even make sense to evaluate the event's transmission at a precise time?

**Comment by SimonHeybrock** [comment]
The current conclusion is that we will try the functional approach. I think it is going to work. Conceptually this is nice, since it further decouples the data reduction workflow from the polarization analysis: There is no need for the data reduction workflow to be aware of any time or wavelength scales of the polarization equipment. The data reduction will return in event mode, with preserved time and wavelength for each event. These will be used to compute the factors for applying the polarization correction.

**Comment by astellhorn** [comment]
>     * The data reduction workflow must perform normalization, e.g., to monitors. Therefore, monitor data must be averaged over a certain time interval. Events can keep higher time resolution, but given that the monitors cannot, does it even make sense to evaluate the event's transmission at a precise time?

Comment:
- I discussed shortly with SANS people from ISIS - and it would be anyhow better if the monitor is integrated just over the same time frame as the events to be corrected for polarization analysis, because of possible fluctuations in intensity from the source. 
- There are different opinions in generel if that approach is better (same time intervals for monitor and data, or integrating monitor over longer time). At ISIS they concluded the former solution is better

**Comment by SimonHeybrock** [comment]
We can (and should, I suppose) still perform time-dependent monitor normalization with what I suggested above. But the time scale is independent from anything we do for the polarization correction.

**Comment by astellhorn** [comment]
Agreed
