### ISSUE TITLE
Implement missing supermirror function

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/esspolarization#65]
See https://github.com/scipp/esspolarization/blob/123b96a89df3a654771c0dcca41870e5e32df661/src/ess/polarization/supermirror.py#L13-L16.

@astellhorn can you provide the required equations?

**Comment by astellhorn** [comment]
Can we add one example where the supermirror efficiency funtion is a polynomial of 2nd order, i.e. Efficiency = a + b*lambda + c*lambda*lambda, and one can set a, b, c? Then the transmission function of that efficiency function with parallel and antiparallel neutron states (T+ and T- values in the SM matrix) is: T_\pm = (1 \pm E)/2. Here, "parallel" means "parallel to the guide field, i.e., to the setting of the SM"
